file = open ("codingal.txt","r")
print (file.read())
file.close()
file = open ("codingal.txt","r")
file = open('codingal.txt','r')
print("\n read in parts \n")
print(file.read(8))
file.close()
file = open('codingal.txt','a')
file . write("Hi I am penguin and i am 1 yr old.")
file.close()